indent_style="Block"
tab_spaces=2
#combine_control_exr=false
enum_discrim_align_threshold=30
merge_imports=true
normalize_comments=true
report_todo="Always"
report_fixme="Always"
space_before_colon=true
struct_field_align_threshold=20
use_field_init_shorthand=true
use_try_shorthand=true
#format_code_in_doc_comments=true
wrap_comments=true
normalize_doc_attributes=true
