[package]
name = "wellcaffeinated/spdcalc"
version = "0.1.3"
description = "WASM package for the SPDCalc library"
readme = "README.md"

[[module]]
name = "spdcalc"
source = "spdcalc.wasm"
abi = "wasi"

[module.bindings]
wai-version = "0.2.3"
exports = "spdcalc.wai"
