[tasks.build]
command = "cargo"
args = ["build"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.lint]
install_crate = { rustup_component_name = "clippy" }
command = "cargo"
args = ["clippy"]

[tasks.docs]
command = "cargo"
args = ["doc", "--no-deps"]

[tasks.format]
command = "cargo"
toolchain = "nightly"
args = ["fmt"]
