default: test-js

build-wapm:
  echo "Building locally"
  # cargo wapm -d --out-dir ./wapm
  # cargo build --target wasm32-unknown-unknown
  # cp target/wasm32-unknown-unknown/release/spdcalc.wasm wapm/

  # RUSTFLAGS='-C target-feature=+atomics,+bulk-memory,+mutable-globals' \
  #   rustup run nightly-2023-05-31 \
  #   cargo build --target wasm32-wasi --release
  cargo build --target wasm32-wasi --release
  cp target/wasm32-wasi/release/spdcalc.wasm wapm/
  cp spdcalc.wai wapm/

build-js: build-wapm
  wasmer-pack js ./wapm --out-dir ./js

build-py: build-wapm
  # RUSTFLAGS='-C target-feature=+atomics,+bulk-memory,+mutable-globals' \
  #   rustup run nightly-2023-05-31 \
  #   wasmer-pack python ./wapm --out-dir ./py/package
  wasmer-pack python ./wapm --out-dir ./py/package

publish-py-test: build-py
  cd {{justfile_directory()}}/py/package && \
    rm dist/* && \
    python3 -m build && \
    python3 -m twine upload --repository testpypi dist/*

test-js: build-js
  pnpm --dir {{justfile_directory()}}/js/package install
  node js/index.mjs

test-py: build-py
  python3 py/test.py