[tasks.build]
install_crate = { crate_name = "maturin", binary = "maturin", test_arg = "--help" }
toolchain = "nightly"
command = "pipenv"
args = ["run", "maturin", "build", "--release"]
dependencies = ["pip_install"]

[tasks.build-cffi]
install_crate = { crate_name = "maturin", binary = "maturin", test_arg = "--help" }
toolchain = "nightly"
command = "pipenv"
args = ["run", "maturin", "build", "-b", "cffi", "--release"]
dependencies = ["pip_install"]

[tasks.publish]
install_crate = { crate_name = "maturin", binary = "maturin", test_arg = "--help" }
toolchain = "nightly"
command = "pipenv"
args = ["run", "maturin", "publish", "--release"]
dependencies = ["pip_install"]

[tasks.dev]
install_crate = { crate_name = "maturin", binary = "maturin", test_arg = "--help" }
toolchain = "nightly"
command = "pipenv"
args = ["run", "maturin", "develop"]
dependencies = ["pip_install"]

[tasks.pip_install]
command = "pipenv"
args = ["install", "--dev"]

# [tasks.docs]
# command = "cargo"
# toolchain = "nightly"
# args = ["doc", "--no-deps"]

# [tasks.docs]
# install_crate = "cargo-sphinx"
# command = "cargo"
# args = ["sphinx"]

[tasks.sphinx]
command = "pipenv"
args = ["run", "sphinx-build", "-b", "html", "docs", "docs/_build"]

[tasks.docs]
dependencies = ["pip_install", "sphinx"]

[tasks.docs-publish]
command = "bash"
args = ["docs/deploy.sh"]
dependencies = ["docs"]

# [tasks.pip_dev]
# toolchain = "nightly"
# command = "pipenv"
# args = ["run", "maturin", "develop"]
# dependencies = ["pip_install"]

[tasks.clean_pip]
command = "pipenv"
args = ["--rm"]

[tasks.clean]
command = "cargo"
args = ["clean"]
dependencies = ["clean_pip"]

[tasks.format]
command = "cargo"
toolchain = "nightly"
args = ["fmt"]

[tasks.test]
command = "cargo"
toolchain = "nightly"
args = ["test", "--all-features"]
