[tasks.build]
install_crate = { crate_name = "maturin", binary = "maturin", test_arg = "--help" }
toolchain = "nightly"
command = "maturin"
args = ["build"]

[tasks.dev]
install_crate = { crate_name = "maturin", binary = "maturin", test_arg = "--help" }
toolchain = "nightly"
command = "pipenv"
args = ["run", "maturin", "develop", "--release"]
dependencies = ["pip_install"]

[tasks.pip_install]
command = "pipenv"
args = ["install", "--dev"]

# [tasks.pip_dev]
# toolchain = "nightly"
# command = "pipenv"
# args = ["run", "maturin", "develop"]
# dependencies = ["pip_install"]

[tasks.release]
install_crate = { crate_name = "maturin", binary = "maturin", test_arg = "--help" }
toolchain = "nightly"
command = "maturin"
args = ["build", "--release", "-i", "python3"]

[tasks.clean_pip]
command = "pipenv"
args = ["--rm"]

[tasks.clean]
command = "cargo"
args = ["clean"]
dependencies = ["clean_pip"]

[tasks.format]
command = "cargo"
toolchain = "nightly"
args = ["fmt"]

[tasks.test]
command = "cargo"
toolchain = "nightly"
args = ["test", "--all-features"]
