[tasks.build]
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "--help" }
command = "wasm-pack"
args = ["build"]

[tasks.cargo_clean]
command = "cargo"
args = ["clean"]

[tasks.pkg_clean]
script = [
  "rm -rf pkg"
]

[tasks.clean]
dependencies = [
  "cargo_clean",
  "pkg_clean",
]

[tasks.format]
command = "cargo"
toolchain = "nightly"
args = ["fmt"]
